# Generated by Django 5.0.6 on 2026-07-01 07:50

import apps.alerts.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=50)),
                ('min_magnitude', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(default=apps.alerts.models._make_token, editable=False, max_length=64, unique=True)),
                ('last_notified_event_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='locationwatch',
            constraint=models.UniqueConstraint(fields=('email', 'latitude', 'longitude'), name='unique_watch_per_email_location'),
        ),
    ]
