# Generated by Django 5.0.6 on 2026-07-01 06:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDisaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('event_date', models.DateField()),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('epicenter', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('casualties', models.IntegerField(blank=True, null=True)),
                ('displaced', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
