upstream gempawatch_backend {
    server backend:8000;
}

upstream gempawatch_frontend {
    server frontend:3000;
}

server {
    listen 80;
    server_name gempawatch.id www.gempawatch.id;

    client_max_body_size 10M;

    # Django REST API
    location /api/ {
        proxy_pass http://gempawatch_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django admin + static
    location /admin/ {
        proxy_pass http://gempawatch_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
    }

    # Next.js frontend
    location / {
        proxy_pass http://gempawatch_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
