# Generated by Django 5.0.6 on 2026-07-01 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('fault_type', models.CharField(blank=True, choices=[('strike-slip', 'Strike-slip'), ('thrust', 'Thrust'), ('normal', 'Normal'), ('megathrust', 'Megathrust')], max_length=20)),
                ('source_citation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
