# Generated by Django 5.0.6 on 2026-07-01 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('BMKG', 'BMKG'), ('USGS', 'USGS')], db_index=True, max_length=8)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('magnitude', models.FloatField(db_index=True)),
                ('depth_km', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.TextField(blank=True)),
                ('felt_reports', models.TextField(blank=True, null=True)),
                ('potensi_tsunami', models.BooleanField(blank=True, null=True)),
                ('shakemap_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
    ]
