# Generated by Django 5.0.6 on 2026-07-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earthquakes', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquakeevent',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='regions.adminregion'),
        ),
        migrations.AddIndex(
            model_name='earthquakeevent',
            index=models.Index(fields=['-event_time', 'magnitude'], name='earthquakes_event_t_55ae79_idx'),
        ),
        migrations.AddIndex(
            model_name='earthquakeevent',
            index=models.Index(fields=['source', '-event_time'], name='earthquakes_source_b6edfb_idx'),
        ),
    ]
