# Generated by Django 5.0.6 on 2026-07-01 06:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earthquakes', '0001_initial'),
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('type', models.CharField(choices=[('provinsi', 'Provinsi'), ('kabupaten', 'Kabupaten'), ('kota', 'Kota')], db_index=True, max_length=20)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_coastal', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='regions.adminregion')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_count_m4', models.IntegerField(default=0)),
                ('event_count_m5', models.IntegerField(default=0)),
                ('event_count_m6', models.IntegerField(default=0)),
                ('event_count_m7_plus', models.IntegerField(default=0)),
                ('largest_magnitude', models.FloatField(blank=True, null=True)),
                ('avg_depth_km', models.FloatField(blank=True, null=True)),
                ('nearest_fault_distance_km', models.FloatField(blank=True, null=True)),
                ('tsunami_risk_tier', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=10, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('largest_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='earthquakes.earthquakeevent')),
                ('nearest_fault', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='faults.faultline')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='regions.adminregion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='adminregion',
            index=models.Index(fields=['type', 'name'], name='regions_adm_type_5ff273_idx'),
        ),
    ]
