# Generated by Django 5.0.6 on 2026-07-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionriskprofile',
            name='activity_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionriskprofile',
            name='activity_tier',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regionriskprofile',
            name='composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionriskprofile',
            name='earliest_event_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionriskprofile',
            name='latest_event_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionriskprofile',
            name='shallow_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
